function TampilProyek1() {
  document.getElementById("iniTabelproyek1").style.display = "";
  document.getElementById("iniTabelproyek2").style.display = "none";
  document.getElementById("iniTabelproyek3").style.display = "none";
  document.getElementById("iniTabelMahasiswa").style.display = "none";
  document.getElementById("iniTabelDosen").style.display = "none";
  document.getElementById("textproyek1").style.display = "";
  document.getElementById("textproyek2").style.display = "none";
  document.getElementById("textproyek3").style.display = "none";
  document.getElementById("textmahasiswa").style.display = "none";
  document.getElementById("textdosen").style.display = "none";
}
function TampilProyek2() {
  document.getElementById("iniTabelproyek1").style.display = "none";
  document.getElementById("iniTabelproyek2").style.display = "";
  document.getElementById("iniTabelproyek3").style.display = "none";
  document.getElementById("iniTabelMahasiswa").style.display = "none";
  document.getElementById("iniTabelDosen").style.display = "none";
  document.getElementById("textproyek1").style.display = "none";
  document.getElementById("textproyek2").style.display = "";
  document.getElementById("textproyek3").style.display = "none";
  document.getElementById("textmahasiswa").style.display = "none";
  document.getElementById("textdosen").style.display = "none";
}
function TampilProyek3() {
  document.getElementById("iniTabelproyek1").style.display = "none";
  document.getElementById("iniTabelproyek2").style.display = "none";
  document.getElementById("iniTabelproyek3").style.display = "";
  document.getElementById("iniTabelMahasiswa").style.display = "none";
  document.getElementById("iniTabelDosen").style.display = "none";
  document.getElementById("textproyek1").style.display = "none";
  document.getElementById("textproyek2").style.display = "none";
  document.getElementById("textproyek3").style.display = "";
  document.getElementById("textmahasiswa").style.display = "none";
  document.getElementById("textdosen").style.display = "none";
}
function TampilMahasiswa() {
  document.getElementById("iniTabelproyek1").style.display = "none";
  document.getElementById("iniTabelproyek2").style.display = "none";
  document.getElementById("iniTabelproyek3").style.display = "none";
  document.getElementById("iniTabelMahasiswa").style.display = "";
  document.getElementById("iniTabelDosen").style.display = "none";
  document.getElementById("textproyek1").style.display = "none";
  document.getElementById("textproyek2").style.display = "none";
  document.getElementById("textproyek3").style.display = "none";
  document.getElementById("textmahasiswa").style.display = "";
  document.getElementById("textdosen").style.display = "none";
}
function TampilDosen() {
  document.getElementById("iniTabelproyek1").style.display = "none";
  document.getElementById("iniTabelproyek2").style.display = "none";
  document.getElementById("iniTabelproyek3").style.display = "none";
  document.getElementById("iniTabelMahasiswa").style.display = "none";
  document.getElementById("iniTabelDosen").style.display = "";
  document.getElementById("textproyek1").style.display = "none";
  document.getElementById("textproyek2").style.display = "none";
  document.getElementById("textproyek3").style.display = "none";
  document.getElementById("textmahasiswa").style.display = "none";
  document.getElementById("textdosen").style.display = "";
}
